


# This task configures /etc/network/interfaces on ifupdown2. The variables for
# which interfaces are neighbors and networks come from the group_vars/all file.
- name: configure networking
  nclu:
      atomic: true
      description: "configure all the newtorking"
      template: |
            add interface eth0 ip address dhcp
            add loopback lo ip address {{ interfaces[ansible_hostname].loopback }}/32

            {% for iface in interfaces[ansible_hostname].neighbors %}
            add interface {{ iface }}
            {% endfor %}

            {% for network in interfaces[ansible_hostname].networks | default(()) %}
            {% for port in interfaces[ansible_hostname].networks[network].ports %}
            add vlan {{ network }}
            add interface {{ port }} bridge access {{ network }}

            {% endfor %}
            add bridge bridge ports {{ " ".join(interfaces[ansible_hostname].networks[network].ports) }}
            net add bridge bridge ports vxlan10{{ network }}
            net add bridge bridge vids {{ network }}
            net add vxlan vxlan10{{ network }} vxlan id 1010
            net add vxlan vxlan10{{ network }} bridge access {{ network }}
            {% endfor %}

            add bgp autonomous-system {{ interfaces[ansible_hostname].asn }}
            add bgp router-id {{ interfaces[ansible_hostname].loopback }}
            add bgp network {{ interfaces[ansible_hostname].loopback }}/32

            add bgp maximum-paths 64
            add bgp bestpath as-path multipath-relax
            add bgp bestpath compare-routerid
            add bgp neighbor fabric peer-group
            add bgp neighbor fabric description Internal Fabric Network
            add bgp neighbor fabric capability extended-nexthop
            add bgp neighbor fabric advertisement-interval 0
            add bgp neighbor fabric timers 1 3
            add bgp neighbor fabric timers connect 3
            add bgp neighbor fabric remote-as external
            add bgp ipv6 unicast neighbor fabric activate
            {% for neighbor in interfaces[ansible_hostname].neighbors %}
            add bgp neighbor {{ neighbor }} peer-group fabric
            add bgp ipv6 unicast neighbor {{ neighbor }} activate
            add bgp evpn neighbor {{ neighbor }} activate 
            {% endfor %}

            {% if interfaces[ansible_hostname].type == "leaf" %}
            add bgp evpn advertise-all-vni
            {% endif %}            

            add routing prefix-list ipv4 dc-fabric-in seq 10 permit 0.0.0.0/0
            add routing prefix-list ipv4 dc-fabric-in seq 20 permit 10.0.0.0/24 le 32
            add routing prefix-list ipv4 dc-fabric-in seq 500 deny any

            add routing prefix-list ipv4 dc-fabric-out seq 20 permit 10.0.0.0/24 le 32
            add routing prefix-list ipv4 dc-fabric-out seq 500 deny any

            add bgp neighbor fabric prefix-list dc-fabric-in in
            add bgp neighbor fabric prefix-list dc-fabric-out out

#
